name: Pull Request Reminder

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  reminder:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
      issues: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Pull Request Info
        id: pr_info
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });

            const author = pr.data.user.login;
            const labels = pr.data.labels.map(label => label.name);

            return { author, number, labels };

      - name: Check if Reminder Needed
        id: check_reminder
        uses: actions/github-script@v7
        with:
          script: |
            const { labels } = ${{ steps.pr_info.outputs }};
            const reminderLabel = 'reminder sent';

            if (!labels || labels.length === 0) { 
              sendReminder = true; // send reminder if the time threshold is passed, even without labels.
            }
            if (labels.includes(reminderLabel)) {
              sendReminder = false;
            }
            console.log("sendReminder value:", sendReminder); // Added debug log
            return { sendReminder: sendReminder };

      - name: Debug Output
        run: echo "check_reminder.outputs: ${{ toJSON(steps.check_reminder.outputs) }}"

      - name: Debug PR Info
        run: echo "pr_info.outputs: ${{ toJSON(steps.pr_info.outputs) }}"

      - name: Send Reminder Comment
        if: ${{ steps.check_reminder.outputs.sendReminder == true }}
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number, author } = ${{ steps.pr_info.outputs }};
            const message = `@${author}, please make sure that you update the files in Heretto and post the Heretto share link in this PR.`;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: message,
            });

      - name: Add Reminder Label
        if: ${{ steps.check_reminder.outputs.sendReminder == true }}
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = ${{ steps.pr_info.outputs }};
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: number,
              labels: ['reminder sent'],
            });
